export TOOL_DIR='${__tool_directory__}' &&

Rscript '${__tool_directory__}/'skewer_render.R

	-o '$report'
	-d '$report.files_path'
	-s '$sink_message'
	-A '$first_reads'
	-B '$second_reads'
	-x '$adapter_first_reads'
	-y '$adapter_second_reads'
	-m '$trimming_mode'
	-r '$maximum_allowed_error_rate'
	-D '$maximum_allowed_indel_error_rate'
	-q '$quality_trimming_3_end'
	-Q '$mean_quality'
	-l '$minimum_read_length'
	-j '$advanced_options.junction_adapter'
	-M '$advanced_options.tab_adapter'
	-b '$advanced_options.barcode'
	-c '$advanced_options.cut'
	-n '$advanced_options.filter_degenerative_reads'
	-u '$advanced_options.filter_undetermined_mate_pair_reads'
	-f '$advanced_options.format'
	-z '$advanced_options.compress'
	-E '$advanced_options.qiime'
	-F '$advanced_options.quiet'
	-i '$advanced_options.intelligent'
	-1 '$trimmed_r1'
	-2 '$trimmed_r2'
	-3 '$trimmed_s'
