---
title: "Aurora Galaxy Tool Reports"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

This site demonstrates example tool reports from a set of Aurora Galaxy tools, including 
both single HTML report tools and website report tools. Source code for these tools can be
found at [https://github.com/statonlab/aurora-galaxy-tools](https://github.com/statonlab/aurora-galaxy-tools). 
Tools are also available at the [Galaxy Test ToolShed](https://testtoolshed.g2.bx.psu.edu/).

## Single HTML reports

* [aurora_skewer](aurora_skewer/rmarkdown_report.html)
* [aurora_fastqc](aurora_fastqc/rmarkdown_report.html)
* [aurora_star](aurora_star/rmarkdown_report.html)
* [aurora_htseq](aurora_htseq/rmarkdown_report.html)
* [aurora_deseq2](aurora_deseq2/rmarkdown_report.html)

## Website reports

* [aurora_skewer_site](aurora_skewer_site/index.html)
* [aurora_fastqc_site](aurora_fastqc_site/index.html)
* [aurora_star_site](aurora_star_site/index.html)
* [aurora_htseq_site](aurora_htseq_site/index.html)
* [aurora_deseq2_site](aurora_deseq2_site/index.html)

